### ISSUE TITLE
SNMP configuration for new switch

### ISSUE THREAD

**Issue by sri4kanne** [brocade/ansible#33]
Can you please post a sample configuration for snmpv1 and snmpv3 configuration in new switch setup? 
https://github.com/brocade/ansible/blob/master/tasks/switch_initial_config.yml#L149 - has option to enable/disable can you please post a sample config where we can update the trap recipient ip/port for the same?
command that's used on switch itself is - snmpconfig --set snmpv1/snmpv3

**Comment by daniel-chung-broadcom** [comment]
Let me look into it. I'll keep you posted.

**Comment by daniel-chung-broadcom** [comment]
can you please check out snmp_config branch? I have facts_snmp.yml and snmp.yml that has some examples. I haven't done full testing on this but I wanted to see if this is along the line of what you are looking for. thanks.

**Comment by sri4kanne** [comment]
this is exactly what i was looking for, thanks. I did try it out and works as expected.
We are able to configure the switch using ansible playbooks now except for configuring relay server. Do you have any plans to add that too? 
Thank you agin for the quick turnaround.

**Comment by daniel-chung-broadcom** [comment]
great. I'll plan to hold on to the changes on the side branch and once we merge everything into the main, I'll plan to close the issue.

as for relayconfig, I'll need to do some research to see if we have rest coverage. I think it might be possible to cover using ssh mechanism but might take longer to implement that if needed. I'll keep you posted.

**Comment by sri4kanne** [comment]
Sounds good, thanks.

**Comment by daniel-chung-broadcom** [comment]
I think that you are looking for are under brocade-maps module.
 
     leaf domain-name {
        type string {
          length "4..63";
          pattern "([a-zA-Z]{0,1}[0-9a-zA-Z_]{2,3}[0-9a-zA-Z_]{4,63})";
        }
        description 
        "
        The domain name. Enter none to clear the name.
        ";
      }
      leaf relay-ip-address {
        type inet:ip-address;
        description 
          "
          The relay IP address. Enter none to clear the IP address.
          ";
      }

**Comment by daniel-chung-broadcom** [comment]
I think I found the right rest attributes. 

Can you please check out the latest snmp_config branch? I added facts_relay_server.yml and relay_server.yml. I just ran once and verified that relayconfig --show display the matching info.

**Comment by sri4kanne** [comment]
It works with only ip and domain name. It's failing when i try to overwrite any information that already exists but works fine adding new or when i run playbook with same values that already exists. And we would need other attributes which i have included below too.

  - name: configure relay server
    brocade_singleton_obj:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade-maps"
      obj_name: "maps-config"
      attributes:
        relay_ip_address: "relayserver.d.com"
        domain_name: "d.com"
        sender_address: brocade_alert@d.com
        recipient_address_list:
          recipient_address: user@d.com

TASK [configure relay server] *****************************************************************************************************************************************
fatal: [lsfcsw6103]: FAILED! => {"attributes": {"domain_name": "d.com", "recipient_address_list": {"recipient_address": "user@d.com"}, "relay_ip_address": "relayserver.d.com", "sender_address": "brocade_alert@d.com"}, "changed": false, "diff_attributes": {"recipient-address-list": {"recipient-address": "user@d.com"}}, "msg": "url_patch failed", "patch_obj_str": "<maps-config><recipient-address-list>{'recipient-address': 'user@d.com'}</recipient-address-list></maps-config>", "patch_resp_code": 400, "patch_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "16715778", "error-module": "cal"}, "error-message": "Invalid input data", "error-path": "/rest/running/brocade-maps/maps-config", "error-tag": "operation-failed", "error-type": "application"}}}, "patch_resp_reason": "Bad Request", "patch_url": "https://********/rest/running/brocade-maps/maps-config", "resp_attributes": {"actions": {"action": ["raslog", "snmp-trap", "e-mail", "port-fence", "sfp-marginal", "decomission", "fms", "un-quarantine", "sw-critical", "sw-marginal", "sddq"]}, "decommission_cfg": "with-disable", "domain_name": "d.com", "recipient_address_list": {"recipient_address": "user@d.com"}, "relay_ip_address": "relayserver.d.com", "sender_address": "brocade_alert@d.com"}, "ssh_hostkeymust": true}

**Comment by daniel-chung-broadcom** [comment]
can you pull down snmp_config latest and give another try? I have an example of the recipient address structure in the relay_server.yml.

**Comment by daniel-chung-broadcom** [comment]
fyi. just pushed some additional changes to provide longer rest timeout than the default ansible value of 10. I noticed that updating all v1 accounts occasionally trigger rest timeout while I am testing. I added longer_timeout attribute and set it to 30 for that specific operations for brocade_list_obj module.

just out of curiosity, are you able to share the scope of your project and which company that you work for? If you prefer to keep it under the wrap, no need to share. Also, if you prefer to send me a direct email instead of github, you can use daniel.chung@broadcom.com. Please don't feel compelled to share. This is just a personal and friendly curiosity on my part.

**Comment by sri4kanne** [comment]
ya it worked now thanks! :) 
I work for Athenahealth and can definitely share details over email to you early next week including all the details.

Regarding timeout thanks for doing that, i had to add throttle in between for so it would not error with "too busy" which happened during one of the switch setup run. This happened to me when i was using ipfilter module and here i'm getting error when enabling more than one policy at a time
 
  - name: ipfilter policy is activated or active already
    brocade_security_ipfilter_policy:
      credential: "{{credential}}"
      vfid: -1
      active_policy:
        -  "policy1"
        -  "policy2"

So i used which works, i was thinking of using loop function but if you can correct the logic how it's process that would be great.
  - name: ipfilter policy is activated or active already
    brocade_security_ipfilter_policy:
      credential: "{{credential}}"
      vfid: -1
      active_policy: "policy1"
      throttle:  30
      active_policy: "policy2"

**Comment by daniel-chung-broadcom** [comment]
Great. Looking forward to hearing from you on the project details.
 
Apology in advance for a long comment below:

As for throttle and timeout, they actually represent two different things. "throttle" attribute applies to all modules. And it is meant to spread the # of rest request to avoid having to run into 503 server busy error. In 8.2.x, FOS allows 30 requests within 30 seconds. If you exceed that, the next request will trigger 30 seconds of throttling period. During that time, you are only allowed one request every 3 seconds. These values are shown in mgmtapp --show output and 9.0 has some updates to these values. Currently default "throttle" is set to 1.1. This means that we are sleeping 1.1 seconds after each rest request to FOS, in order to come under 30 requests within 30 seconds all the time and to avoid trigger 503 server busy error.

"longer_timeout" on the other hand is to specify a longer time out for rest request. For example, some rest patch operation may take more than 10 seconds because the operation results in saving some data to persistent storage. For those specific operations, we would want to increase the timeout available for the specific operation, so that rest operation doesn't timeout before the response is returned. This attribute is only available for brocade_list_obj at the moment but I can extend to other modules as needed. I noticed that updating all v1 entries would typically result in timeout in the playbook.

Now getting back to ipfilter policy, I believe you mentioned running into "too busy". Can you please confirm that you are seeing HTTP error code 503 server busy? Assuming that you are, I have been working on changing the throttling model within BSN modules and I think that might be helpful in your scenario. Basically, instead of sleeping 1.1 seconds per each rest call, I am executing rest operations as needed until running into 503 server buy error. Once I do, I"ll wait 32 seconds for the throttling period to expire. Then, I'll do one retry. Assuming that it succeeds (it mostly should), we go back executing rest until we get the next 503, and start over all over again. So, the default "throttle" attribute value is changing 32, instead of 1.1 now. 

This basically means that your playbook would probably run faster than before if your playbook consists of a small # of rest calls because there will be no delays being introduced. If you have a lot of # of rest calls that trigger 503, you will notice a play pausing for 32 seconds then continue executing afterward. 

I have both snmp changes and the throttling changes in snmp_config_new_throttle branch. Please check it out when you get a chance. Also, let me know if ip filter issue is something different.

**Comment by sri4kanne** [comment]
Thanks for the detailed explanation, yes i was receiving 503 error. This correlates to your explanation where i was trying to run several modules which are part of initial switch setup along with zoning, so adding throttle avoided it as expected.
Also i have run into similar timing issue when when enabling config after creating/delating a bunch of zones and alias.  Also i did notice you added "- pause: seconds=15" in the play and this looks like serving the same purpose as "throttle" ? 

regarding ipfilter issue: there were 2 issues that i came across
1. 503 error - which i was able to make it work by adding "throttle: 30" before enabling the policy and i believe this has more to do with several other modules i ran before ipfilter module and crossed the limit. I believe bumping up the threshold should fix it, will try out and let you know if i run into it again. 
2. I am able to create multiple rules and policy but when i try enable more than one policy i get below error, and below is the task that i'm using. ( I am able to enable one policy using active_policy but not more than one) 

  - name: activate default ipv4 before deleting previously created custom policy
    brocade_security_ipfilter_policy:
      credential: "{{credential}}"
      vfid: -1
      active_policy:
        - BlockTelnetHTTPipv4
        - BlockTelnetHTTPipv6 

PLAY [All] ************************************************************************************************************************************************************

TASK [ipfilter policy is activated or active already] *****************************************************************************************************************
[WARNING]: The value ['BlockTelnetHTTPipv4', 'BlockTelnetHTTPipv6'] (type list) in a string field was converted to "['BlockTelnetHTTPipv4', 'BlockTelnetHTTPipv6']"
(type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
fatal: [switch2]: FAILED! => {"changed": false, "msg": "could not find matching policy"}

**Comment by daniel-chung-broadcom** [comment]
for issue #1, I would suggest running snmp_config_new_throttle and see if that helps. since it is now doing one retry after running into 503, you may no longer see failure but 32-second delay at times. 

btw, I am bit surprised that you ran into 503 because we are still doing 1.1 second sleep per each rest request. Were you running other rest tasks in parallel? 

for issue #2, active_policy is defined as a string in brocade_security_ipfilter_policy module. It looks like you were using it as an array in your task and ansible converted the array to string based on the warning shown. So, I believe the right way to use it is to create two separate tasks to enable one then to enable the other. I am not much of ipfilter expert. So, I didn't know if enabling multiple policies is typical or not. Let me know if you feel that is a critical use case and, for one reason or another, separating them out to multiple tasks won't work properly.  

name: enable v4
brocade_security_ipfilter_policy:
credential: "{{credential}}"
vfid: -1
active_policy: BlockTelnetHTTPipv4

name: enable v6
brocade_security_ipfilter_policy:
credential: "{{credential}}"
vfid: -1
active_policy: BlockTelnetHTTPipv6

**Comment by sri4kanne** [comment]
I am running tasks in series. I have total of 23 tasks in the playbook.
I just tried to run the playbook without throttle and worked fine without any issue after you increased the timeout. 

Ya, i have been using it as you mentioned and works fine without any issue and will continue to use it as 2 tasks. Thanks again for all your help!

**Comment by daniel-chung-broadcom** [comment]
sounds good. It looks like all the issues on this thread are addressed. Let me know if anything remaining.

As before, I'll hold onto these changes for some time. I'll go ahead and close the issue once merged to main and released on galaxy.ansible.com.

Thanks.

**Comment by sri4kanne** [comment]
I just noticed today that when i try to overwrite an existing relay_ip address it fails with "https 400" error. Is it possible to update this module aswell similar to others where it will overwrite if something already exsists?

**Comment by daniel-chung-broadcom** [comment]
not sure if I understand the scenario.

  - name: configure relay server
    brocade_singleton_obj:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade-maps"
      obj_name: "maps-config"
      attributes:
        relay_ip_address: "10.10.10.11"
        domain_name: "dd.com"
        sender_address: "s@dd.com"
        recipient_address_list:
          recipient_address:
           - "r@dd.com"
           - "r@rr.com"


are you talking about a case where you set the relay_ip_address to something else (like 10.10.10.12) and run the playbook again?

**Comment by sri4kanne** [comment]
Yes, when i have relay_ip_address already set to "10.10.10.11" and if i run playbook to change it to "10.10.10.12" it's failing with status 400.

**Comment by daniel-chung-broadcom** [comment]
Is this what you are getting?

fatal: [san_eng_zone_seed_san_a]: FAILED! => {"PATCH_resp_code": 400, "PATCH_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "-1", "error-module": "cal"}, "error-message": "Please configure both Relay IP and Domain Name", "error-path": "/maps-config/", "error-tag": "Operation-failed", "error-type": "application"}}}, "PATCH_resp_reason": "Bad Request", "PATCH_url": "http://********/rest/running/brocade-maps/maps-config", "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "attributes": {"domain_name": "d.com", "recipient_address_list": {"recipient_address": ["r@dd.com", "r@rr.com"]}, "relay_ip_address": "10.10.10.12", "sender_address": "s@dd.com"}, "changed": false, "diff_attributes": {"relay-ip-address": "10.10.10.12"}, "msg": "PATCH failed", "patch_obj_str": "<maps-config><relay-ip-address>10.10.10.12</relay-ip-address></maps-config>", "resp_attributes": {"actions": {"action": ["sfp-marginal", "sw-critical", "sw-marginal"]}, "decommission_cfg": "with-disable", "domain_name": "d.com", "recipient_address_list": {"recipient_address": ["r@dd.com", "r@rr.com"]}, "relay_ip_address": "10.10.10.11", "sender_address": "s@dd.com"}, "ssh_hostkeymust": false}

**Comment by daniel-chung-broadcom** [comment]
I think the error message is coming from rest. It is expecting both IP address and domain name to be changed at the same time, I think. 

"error-message": "Please configure both Relay IP and Domain Name"

**Comment by daniel-chung-broadcom** [comment]
It looks like the the CLI also does not allow you to specify just one. But it does allow you to specify the same value as before (domain_name is set to dd.com already). 

switch_name:FID128:admin> relayconfig --config -rla_ip 10.10.10.12
Domain name not specified
switch_name:FID128:admin> relayconfig --config -rla_ip 10.10.10.12 -rla_dname dd.com

Since bsn ansible module figures out the diff and patch the diff only, I suspect that I"ll need special handling to get around the rest dependencies between these two attributes (return old value from one or the other, fail if one is missing, etc). I think I'll need to think it through a bit since the module that is using to update the relay server is a generic implementation that is meant to work for other objects as well. I'll keep you posted.

**Comment by sri4kanne** [comment]
Yes, looks like same error. Below is the error that i' m running into. Thanks for looking into this.
PS- I have specified both domain name and ip in the play. To recreate the issue you can rerun the play with a different ip and it will fail with same error as below. 

fatal: [switch1]: FAILED! => {"PATCH_resp_code": 400, "PATCH_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "-1", "error-module": "cal"}, "error-message": "Please configure both Relay IP and Domain Name", "error-path": "/maps-config/", "error-tag": "Operation-failed", "error-type": "application"}}}, "PATCH_resp_reason": "Bad Request", "PATCH_url": "https://********/rest/running/brocade-maps/maps-config", "attributes": {"domain_name": "dd.com", "recipient_address_list": {"recipient_address": ["user@dd.com"]}, "relay_ip_address": "relayserver1.dd.com", "sender_address": "brocade_alert@dd.com"}, "changed": false, "diff_attributes": {"recipient-address-list": {"recipient-address": ["user@dd.com"]}, "relay-ip-address": "relayserver1.dd.com"}, "msg": "PATCH failed", "patch_obj_str": "<maps-config><recipient-address-list><recipient-address>user@dd.com</recipient-address></recipient-address-list><relay-ip-address>relayserver1.dd.com</relay-ip-address></maps-config>", "resp_attributes": {"actions": {"action": ["sfp-marginal", "sw-critical", "sw-marginal"]}, "decommission_cfg": "with-disable", "domain_name": "dd.com", "recipient_address_list": {"recipient_address": "user@dd.com"}, "relay_ip_address": "relayserver2.dd.com", "sender_address": "brocade_alert@dd.com"}, "ssh_hostkeymust": true}

**Comment by daniel-chung-broadcom** [comment]
You are correct that specifying both attributes in the playbook does not matter if you just change one of the attributes only. Even if both attributes are specified in the playbook, bsn module filters out the attribute that has not changed. So, what FOS sees is just an update to the IP address in this case. This mechanism works in most of the cases since we shouldn't be HTTP patching an attribute with the same value. 

So, the workaround is to provide both attributes in the playbook and change both at the same time.

btw, do you feel that this is an urgent issue? Otherwise, I was thinking that I could merge the existing changes (changes for this thread, along with zoning defect reported) and address this specific scenario in the next round. please let me know. Thanks.

**Comment by sri4kanne** [comment]
As there is a workaround where we can rewrite both would not say it's urgent but it would be good to correct in the long run. If you can post a comment here once it's fixed in master that would be awesome. Thanks

**Comment by daniel-chung-broadcom** [comment]
sounds good. I'll post a note once I have the accumulated changes merged to master to address earlier issues but leave the issue open until we have changes to address the latest comment.

**Comment by daniel-chung-broadcom** [comment]
fyi. changes to the address the original issues are now merged to master & galaxy. I'll keep you posted on the relay ip issue. thanks.

**Comment by daniel-chung-broadcom** [comment]
when you get a chance, can you please try out the relay_server branch? Basic scenarios that I tested are

1) after "relayconfig --delete", providing relay_ip_address only will return failure
2) after "relayconfig --delete", providing domain_name only will return failure
3) update both relay_ip_address and domain_name in a playbook
4) update only relay_ip_address
5) update only domain_name.

let me know if the change address your use case and if the overall failure scenarios also make sense.

Thanks.

**Comment by sri4kanne** [comment]
All the 5 scenarios seem to work without any issue but it's failing when there are no changes to relay_ip and domain_name. (This was working fine before you made changes)

Example:  i had relay_ip_address: "10.10.10.11" and domain_name: "dd.com" and running the play again with same values is giving me error instead of just retuning ok in ansible with below error. 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'relay_ip_address'
fatal: [prfcsw6104]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/.ansible/tmp/ansible-tmp-1590737491.690416-69501326217550/AnsiballZ_brocade_singleton_obj.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/.ansible/tmp/ansible-tmp-1590737491.690416-69501326217550/AnsiballZ_brocade_singleton_obj.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/.ansible/tmp/ansible-tmp-1590737491.690416-69501326217550/AnsiballZ_brocade_singleton_obj.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.brocade_singleton_obj', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py\", line 196, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_singleton_obj_payload_dhii9zfy/ansible_brocade_singleton_obj_payload.zip/ansible/modules/brocade_singleton_obj.py\", line 221, in <module>\n  File \"/var/folders/3p/pvdh4_kj6tgcms2y2spm3nt4ftvdp0/T/ansible_brocade_singleton_obj_payload_dhii9zfy/ansible_brocade_singleton_obj_payload.zip/ansible/modules/brocade_singleton_obj.py\", line 184, in main\nKeyError: 'relay_ip_address'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Thanks,

**Comment by daniel-chung-broadcom** [comment]
Thanks for letting me know. I verified the no change scenarios before but I must have skipped it after making the last minute change to handle the empty scenarios. I just pushed another set of changes and added no change scenario at the end of #5. Please check it out at your convenience.

Thanks.

**Comment by sri4kanne** [comment]
Thanks, looks good now.

**Comment by daniel-chung-broadcom** [comment]
Great. As before, I'll hold on to the changes to accumulate with others. I'll close the issue once the changes are merged to master and published on galaxy. Thanks.

**Comment by daniel-chung-broadcom** [comment]
changes merged to main and uploaded to galaxy.
