### ISSUE TITLE
Zoning recent changes

### ISSUE THREAD

**Issue by sri4kanne** [brocade/ansible#39]
I have been using these modules for a little while now and looks like recent changes made to alias and zones module have changed the feature. Not sure if this was intentional? 
The use case that we have been using is:
- Store all the zoning as config in git and when there was a change to zoning we would update the repo then would run the zoning playbook. Where the git repo is the source of truth which has same config on the switch always. 

Issue: Before whatever was there in the config file would be used to create zones and whatever is not there would be removed. But looks like recent changes is **NOT** removing the deleted config from the repo from the switch zoning DB. 

PS: This was working as expected before i pulled the recent changes to support https://github.com/brocade/ansible/issues/33 and merged it.

Please let me know if you need any more details. Thank you for your help!

**Comment by daniel-chung-broadcom** [comment]
I am not sure if I understand the issue clearly. I think some examples, might be helpful. Zone tasks have always been "additive" and you needed specific delete zone tasks to delete the zones that are no longer needed. Only the members of zones/alias/cfg were "full members" where add/delete/update applies in one shot.

Anyway, please send me some examples from your playbook and I'll look into the details and get back to you.

**Comment by sri4kanne** [comment]
Attached zoning.txt is the playbook used, vars.txt is the vars file before running playbook (also matches current zoning configuration on the switch) and vars_updated is used to run the zoning playbook. Now if i want to change the name host049b --> host050b, If i update the name in vars file and run the playbook instead of renaming the aliases, zones on the switch new aliases and zone is created for host050b but also the old zones and aliases for host049b exists now. But before when we would do the same changes and run the same playbook instead we would not see aliases and zones for host049b but only for host050b as expected. Hopefully this helps to clarify the example, please let me know if you need more details.


[zoning.txt](https://github.com/brocade/ansible/files/4802334/zoning.txt)
[vars.txt](https://github.com/brocade/ansible/files/4802333/vars.txt)
[vars_updated.txt](https://github.com/brocade/ansible/files/4802360/vars_updated.txt)

**Comment by daniel-chung-broadcom** [comment]
Looking at the files, the behavior that you are seeing is expected as far as I understand. I have not made any changes in this area and alias/zone/cfg were originally designed to be additive only. i.e. new zones are added but zones not specified are not deleted. This was to accommodate the use case where the user may be managing only a portion of the zoning using Ansible and want to leave the rest of the zone DB as is. In order to delete the zones, aliases_to_delete/zones_to_delete/cfgs_to_delete have to be given explicitly.

So, in your case, host050b is considered new and added. And host049b is considered deleted and ignored until you specify it in aliases_to_delete. This is because alias/zone/cfg are indexed based on the name attribute as a key. So, Ansible Zoning module thinks that host050b is just a new entry altogether and there is no way of knowing an entry with a different key is meant to be a replacement.

Only the members are added and deleted automatically (unless you provide members_add_only or remember_remove_only at True). i.e. ZoneA (1, 2, 3) will be placed with ZoneA (4) where 4 is added and 1, 2, 3 are removed if not specified as members.

I hope this clarifies. Please let me know if any issues or suggestions.

**Comment by sri4kanne** [comment]
Ok that makes sense, so onl y for the members it works. I have been testing with that for the most part and was not changing names a lot but noticed it when we actually started using on actual switches. Thanks for the explanation will create a delete playbook and use it as needed.

Another unrelated quick question - Is there a brocade switch simulator where we can test playbooks that we can use or we have to rely on using new/dev switches in our environment?

**Comment by daniel-chung-broadcom** [comment]
currently, we do not have a simulator for REST/CLI. So, a real switch is needed to work with ansible modules.

I'll close the issue. Please let me know if any other questions or issues.
