### ISSUE TITLE
(feature request) Configurable DEFAULT_TO

### ISSUE THREAD

**Issue by freedge** [brocade/ansible#59]
right now DEFAULT_TO has a reasonable value of 10 seconds

unfortunately switches can be sometimes slow to connect to. When it takes more than 10s to connect to a switch, ansible will return an error while a session is actually opened (and will last for hours on the switch side). As we have by default, a maximum of 3 sessions on the switch, it's very easy to cause a "denial of service" by mistake.

I personally set it to 30s which fixes my own issue. Is it possible to have a way to configure this time out?

Thanks

**Comment by daniel-chung-broadcom** [comment]
Every module supports "throttle" as one of the arguments. So, you should be able to specify 30 in your playbook, instead of (I am assuming) having fix DEFAULT_TO to 30 from 10.

Here is a quick example of what I mean.

  - name: disable switch
    brocade_fibrechannel_switch:
      credential: "{{credential}}"
      vfid: -1
      **throttle: 30**
      switch:
        enabled_state: False

Let me know if this works according to your expectation.

**Comment by daniel-chung-broadcom** [comment]
I am sorry. I got confused with throttle and DEFAULT_TO usage. throttle gets embedded into the sleep time for retry in the case of server busy. I have ability to specify longer timeout per each module but I don't expose that to be used in different playbooks. Let me go ahead and add "longer_timeout" to each of the modules. There are certain modules that already use 30 seconds - for example v1 account module - explicitly calling for it. Let me look at the changes needed and keep you posted. Sorry for the confusion.

**Comment by daniel-chung-broadcom** [comment]
While working adding "timeout" optional variable to each module, just want to clarify the throttle vs. timeout behavior.

Timeout (DEFAULT_TO) is there to provide for rest connection to last longer for operations that take a long time. For example, generation a CSR typically takes a long time and I use 300 as the timeout value within the module (will be added to playbook with the latest changes btw). Otherwise, the HTTP POST/PATCH operation will timeout while the backend FOS is still working on the request.

Throttle, on the other hand, is provided to allow you to pause before retry if the server is busy. The logic is that you try an operation and if the connection returns server busy, we'll pause for throttle period and retry once more before giving up. By default it is set to 4. This is in response to throttling mechanism implemented on FOS.

Based on your description of having to change DEFAULT_TO to 30 to get things running, I am wondering if you are running into a situation where 10 second default TO wasn't long enough to complete some operations and thus err'ed out.  Although you indicated that you were getting "server busy", which means that you should have updated throttle to bigger value (for example, 12 if you have three active/busy sessions). It is possible that increasing the timeout may have delayed some operations and affected throttle but this is just a guess at the moment. 

I'll have the changes for timeout once I am done with sanity testing. But I just wanted to give some context to timeout and throttle in case it would help to decide what would be the best option for you.

**Comment by daniel-chung-broadcom** [comment]
I have changes added to additional_facts branch? You can use "timeout" variable as optional for any modules available. I have done most of time sanity testing but still remaining few. But I wanted to give you heads-up when I have covered sufficient amount of changes.

  - name: CSR export. Existing CSR is not compared. This task will always change.
    brocade_security_security_certificate_action:
      credential: "{{credential}}"
      vfid: -1
      timeout: 300
      action_inputs: "{{action_inputs}}"

**Comment by freedge** [comment]
Thanks for the work! I will test this next week (unless there is someway I can run this module  without access to a real switch but it does not seem to be possible at the moment)

**Comment by daniel-chung-broadcom** [comment]
this change got pulled in as part of adding additional facts that were requested by another. I'll go ahead and leave the issue open in case you find other issues that need to be addressed related to timeout. Once you give a go ahead, I'll close the issue. I have completed my own sanity testing with the changes.

**Comment by freedge** [comment]
issue [persists](https://dev.azure.com/freedge/freedge/_build/results?buildId=271&view=logs&j=1ebc38c8-fade-5a89-24da-f796855a97f6&t=7e545587-1914-5048-c05b-92ed6ea139f6&l=180) with collection 1.0.21 as https://github.com/brocade/ansible/blob/master/utils/brocade_connection.py#L55 still calls url_helper without a specified timeout, so the default is used.

**Comment by daniel-chung-broadcom** [comment]
Thanks for pointing that out. It looks like I need to pass the timeout to login and call url_helper with it to avoid your issue. I'll keep you posted on the changes.

**Comment by daniel-chung-broadcom** [comment]
can you please try out the supportsave branch? I think I addressed all the places previously missed, including login that you identified. Thanks.

**Comment by freedge** [comment]
that one looks good! thanks

**Comment by daniel-chung-broadcom** [comment]
great. I'll hold unto the changes and merge to master with other changes within next week or two. I'll close the issue then. Thanks.

**Comment by daniel-chung-broadcom** [comment]
the changes are merged with supportsave into master and also copied to galaxy.

**Comment by freedge** [comment]
fixed in brocade.fos 1.0.22. Thanks!

**Comment by daniel-chung-broadcom** [comment]
Great to hear. You are welcome.
