### ISSUE TITLE
Feature Request: Support import of crypto template files

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#74]
I would like to import and activate crypto template files. The CLI equivalent is `seccryptocfg --import` and `seccryptocfg --apply`. The REST API leave is `brocade-security/sec-crypto-cfg-template-action`.

**Comment by daniel-chung-broadcom** [comment]
Will look into the details and keep you posted.

**Comment by daniel-chung-broadcom** [comment]
fyi. uploaded partial changes to documentation_attribute_content_change branch. verified export & apply but still working on figuring out import use case. hopefully, I'll have a resolution next few days.

**Comment by daniel-chung-broadcom** [comment]
I think I am done with my verification. It turns out that the import required the full path name - including file name - unlike other actions that just required path. I created four playbooks and one module. Please try it out and let me know if this is what you are looking for.

facts_sec_crypto_cfg_template.yml  sec_crypto_cfg_template_export.yml
sec_crypto_cfg_template_apply.yml  sec_crypto_cfg_template_import.yml

Thanks.

**Comment by mamoep** [comment]
Works fine, but is not idempotent. 

Maybe change the name attribut in the code documentation to avoid confusion (I also found conflicting names in other modules, propably copy/paste issue): https://github.com/brocade/ansible/blob/dc8fa16f573b8ac252dc0d28adfa2919120b3921/library/brocade_security_sec_crypto_cfg_template_action.py#L76

**Comment by daniel-chung-broadcom** [comment]
I updated the documentation section to reflect that the module is not idempotent. The underlying rest api is implemented as an operation and read/compare of the template content is not supported.

**Comment by mamoep** [comment]
When will you release the changes in the collection?

**Comment by daniel-chung-broadcom** [comment]
merged to collection as 1.2.
