### ISSUE TITLE
Issue with Setup

### ISSUE THREAD

**Issue by rawstorage** [brocade/ansible#9]
Hi, not sure if I have an environment setup issue but getting the following error when trying to run gather_facts

fatal: [mysan]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "get_resp_code": 400, "get_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "5", "error-module": "rest"}, "error-message": "Invalid REST URI", "error-path": "/rest/running/brocade-fibrechannel-switch/fibrechannel-switch", "error-tag": "unknown-element", "error-type": "application"}}}, "get_resp_reason": "Bad Request", "get_url": "http://myIP/rest/running/brocade-fibrechannel-switch/fibrechannel-switch", "msg": "API failed to return switch firmware version"}

ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

switch I'm pointing to..
mgmtapp --show
REST Interface State: Enabled
REST Session Count: 3
REST Throttling Configurations:
   Sample Requests      : 30
   Sample Time (in sec) : 30
   Idle Time (in sec)   : 3

 firmwareshow
Appl     Primary/Secondary Versions
------------------------------------------
FOS      v8.2.0b
         v8.2.0b

**Comment by daniel-chung-broadcom** [comment]
the code is tested using 8.2.1c and the uri for the fibre channel switch changed between 8.2.1a & 8.2.1b. Since the library is tested with 8.2.1c (updated the readme), the code is using the latest uri.

I think the simplest way might be to update the code directly in couple of places to use the old uri for fibre channel switch. 

Under this directory:
library/ansible/module_utils/storage/brocade

These two files:
brocade_connection.py
brocade_fibrechannel_switch.py

Change

REST_SWITCH = "/rest/running/brocade-fibrechannel-switch/fibrechannel-switch"

to

REST_SWITCH = "/rest/running/switch/fibrechannel-switch"

Looking at the code, it seems like that should take care of it.

**Comment by daniel-chung-broadcom** [comment]
one more thing. since 8.2.0b would have less rest coverage than 8.2.1c, most of the modules would continue to return an error even if the initial switch uri returns success. at first glance, I think the obvious modules that might still work are switch, fc port & zoning. I don't believe the rest of the modules have supporting uri in 8.2.0b.

you can also check out 

https://github.com/brocade/ansible-fos-command

to create playbooks using CLI commands regardless of fos versions.

**Comment by daniel-chung-broadcom** [comment]
closing the issue based on the last posting describing the supported FOS version.
